### ISSUE TITLE
Submit for Qt 6

### ISSUE THREAD

**Issue by vimpostor** [misje/once#2]
Have you considered submitting this to Qt codereview? It would be very nice to have this officially in Qt.
Qt 6 will require at least C++11 (maybe even higher), so this implementation should be good to go.

Related Qt bug: https://bugreports.qt.io/browse/QTBUG-44219

**Comment by misje** [comment]
I have indeed thought about it, because this would be a nice `Qt::ConnectionType` flag. All the template nightmare already exists in some form in QtCore. Since C++11 was not a requirement, I dropped the idea. If C++11 is a requirement in Qt 6, then perhaps I should look into it. I am surprised no one has already done it.

**Comment by vimpostor** [comment]
Just an FYI: Qt 6 will require C++17.

**Comment by vimpostor** [comment]
This has just been implemented in Qt 6.0: https://codereview.qt-project.org/c/qt/qtbase/+/311098
Instead of using template magic it uses internal QObject code.

Still props to you though for coming up with this template implementation. :)

**Comment by misje** [comment]
I am happy to see this! I still haven't found the time or energy to look at implementing it myself. Yes, my code needs to do a lot of the logic that Qt already does (i.e. Qt's own "template magic"). Implementing it in qtbase makes a lot of sense.

However, Qt 6 is far away for many of us, so I hope this project will remain useful.
